class RemoveAndAddColumnsFromCompounds < ActiveRecord::Migration[7.0]
    def change
      remove_column :compounds, :AvgIpc, :float
      remove_column :compounds, :BCUT2D_CHGHI, :float
      remove_column :compounds, :BCUT2D_CHGLO, :float
      remove_column :compounds, :BCUT2D_LOGPHI, :float
      remove_column :compounds, :BCUT2D_LOGPLOW, :float
      remove_column :compounds, :BCUT2D_MRHI, :float
      remove_column :compounds, :BCUT2D_MRLOW, :float
      remove_column :compounds, :BCUT2D_MWHI, :float
      remove_column :compounds, :BCUT2D_MWLOW, :float
      remove_column :compounds, :BalabanJ, :float
      remove_column :compounds, :BertzCT, :float
      remove_column :compounds, :Chi0, :float
      remove_column :compounds, :Chi0n, :float
      remove_column :compounds, :Chi0v, :float
      remove_column :compounds, :Chi1, :float
      remove_column :compounds, :Chi1n, :float
      remove_column :compounds, :Chi1v, :float
      remove_column :compounds, :Chi2n, :float
      remove_column :compounds, :Chi2v, :float
      remove_column :compounds, :Chi3n, :float
      remove_column :compounds, :Chi3v, :float
      remove_column :compounds, :Chi4n, :float
      remove_column :compounds, :Chi4v, :float
      remove_column :compounds, :EState_VSA1, :float
      remove_column :compounds, :EState_VSA10, :float
      remove_column :compounds, :EState_VSA11, :float
      remove_column :compounds, :EState_VSA2, :float
      remove_column :compounds, :EState_VSA3, :float
      remove_column :compounds, :EState_VSA4, :float
      remove_column :compounds, :EState_VSA5, :float
      remove_column :compounds, :EState_VSA6, :float
      remove_column :compounds, :EState_VSA7, :float
      remove_column :compounds, :EState_VSA8, :float
      remove_column :compounds, :EState_VSA9, :float
      remove_column :compounds, :ExactMolWt, :float
      remove_column :compounds, :FpDensityMorgan1, :float
      remove_column :compounds, :FpDensityMorgan2, :float
      remove_column :compounds, :FpDensityMorgan3, :float
      remove_column :compounds, :FractionCSP3, :float
      remove_column :compounds, :HallKierAlpha, :float
      remove_column :compounds, :HeavyAtomCount, :integer
      remove_column :compounds, :HeavyAtomMolWt, :float
      remove_column :compounds, :Ipc, :float
      remove_column :compounds, :Kappa1, :float
      remove_column :compounds, :Kappa2, :float
      remove_column :compounds, :Kappa3, :float
      remove_column :compounds, :LabuteASA, :float
      remove_column :compounds, :MaxAbsEStateIndex, :float
      remove_column :compounds, :MaxAbsPartialCharge, :float
      remove_column :compounds, :MaxEStateIndex, :float
      remove_column :compounds, :MaxPartialCharge, :float
      remove_column :compounds, :MinAbsEStateIndex, :float
      remove_column :compounds, :MinAbsPartialCharge, :float
      remove_column :compounds, :MinEStateIndex, :float
      remove_column :compounds, :MinPartialCharge, :float
      remove_column :compounds, :MolLogP, :float
      remove_column :compounds, :MolMR, :float
      remove_column :compounds, :MolWt, :float
      remove_column :compounds, :NHOHCount, :integer
      remove_column :compounds, :NOCount, :integer
      remove_column :compounds, :NumAliphaticCarbocycles, :integer
      remove_column :compounds, :NumAliphaticHeterocycles, :integer
      remove_column :compounds, :NumAliphaticRings, :integer
      remove_column :compounds, :NumAromaticCarbocycles, :integer
      remove_column :compounds, :NumAromaticHeterocycles, :integer
      remove_column :compounds, :NumAromaticRings, :integer
      remove_column :compounds, :NumHAcceptors, :integer
      remove_column :compounds, :NumHDonors, :integer
      remove_column :compounds, :NumHeteroatoms, :integer
      remove_column :compounds, :NumRadicalElectrons, :integer
      remove_column :compounds, :NumRotatableBonds, :integer
      remove_column :compounds, :NumSaturatedCarbocycles, :integer
      remove_column :compounds, :NumSaturatedHeterocycles, :integer
      remove_column :compounds, :NumSaturatedRings, :integer
      remove_column :compounds, :NumValenceElectrons, :integer
      remove_column :compounds, :PEOE_VSA1, :float
      remove_column :compounds, :PEOE_VSA10, :float
      remove_column :compounds, :PEOE_VSA11, :float
      remove_column :compounds, :PEOE_VSA12, :float
      remove_column :compounds, :PEOE_VSA13, :float
      remove_column :compounds, :PEOE_VSA14, :float
      remove_column :compounds, :PEOE_VSA2, :float
      remove_column :compounds, :PEOE_VSA3, :float
      remove_column :compounds, :PEOE_VSA4, :float
      remove_column :compounds, :PEOE_VSA5, :float
      remove_column :compounds, :PEOE_VSA6, :float
      remove_column :compounds, :PEOE_VSA7, :float
      remove_column :compounds, :PEOE_VSA8, :float
      remove_column :compounds, :PEOE_VSA9, :float
      remove_column :compounds, :RingCount, :integer
      remove_column :compounds, :SMR_VSA1, :float
      remove_column :compounds, :SMR_VSA10, :float
      remove_column :compounds, :SMR_VSA2, :float
      remove_column :compounds, :SMR_VSA3, :float
      remove_column :compounds, :SMR_VSA4, :float
      remove_column :compounds, :SMR_VSA5, :float
      remove_column :compounds, :SMR_VSA6, :float
      remove_column :compounds, :SMR_VSA7, :float
      remove_column :compounds, :SMR_VSA8, :float
      remove_column :compounds, :SMR_VSA9, :float
      remove_column :compounds, :SlogP_VSA1, :float
      remove_column :compounds, :SlogP_VSA10, :float
      remove_column :compounds, :SlogP_VSA11, :float
      remove_column :compounds, :SlogP_VSA12, :float
      remove_column :compounds, :SlogP_VSA2, :float
      remove_column :compounds, :SlogP_VSA3, :float
      remove_column :compounds, :SlogP_VSA4, :float
      remove_column :compounds, :SlogP_VSA5, :float
      remove_column :compounds, :SlogP_VSA6, :float
      remove_column :compounds, :SlogP_VSA7, :float
      remove_column :compounds, :SlogP_VSA8, :float
      remove_column :compounds, :SlogP_VSA9, :float
      remove_column :compounds, :TPSA, :float
      remove_column :compounds, :VSA_EState1, :float
      remove_column :compounds, :VSA_EState10, :float
      remove_column :compounds, :VSA_EState2, :float
      remove_column :compounds, :VSA_EState3, :float
      remove_column :compounds, :VSA_EState4, :float
      remove_column :compounds, :VSA_EState5, :float
      remove_column :compounds, :VSA_EState6, :float
      remove_column :compounds, :VSA_EState7, :float
      remove_column :compounds, :VSA_EState8, :float
      remove_column :compounds, :VSA_EState9, :float
      remove_column :compounds, :fr_Al_COO, :integer
      remove_column :compounds, :fr_Al_OH, :integer
      remove_column :compounds, :fr_Al_OH_noTert, :integer
      remove_column :compounds, :fr_ArN, :integer
      remove_column :compounds, :fr_Ar_COO, :integer
      remove_column :compounds, :fr_Ar_N, :integer
      remove_column :compounds, :fr_Ar_NH, :integer
      remove_column :compounds, :fr_Ar_OH, :integer
      remove_column :compounds, :fr_COO, :integer
      remove_column :compounds, :fr_COO2, :integer
      remove_column :compounds, :fr_C_O, :integer
      remove_column :compounds, :fr_C_O_noCOO, :integer
      remove_column :compounds, :fr_C_S, :integer
      remove_column :compounds, :fr_HOCCN, :integer
      remove_column :compounds, :fr_Imine, :integer
      remove_column :compounds, :fr_NH0, :integer
      remove_column :compounds, :fr_NH1, :integer
      remove_column :compounds, :fr_NH2, :integer
      remove_column :compounds, :fr_N_O, :integer
      remove_column :compounds, :fr_Ndealkylation1, :integer
      remove_column :compounds, :fr_Ndealkylation2, :integer
      remove_column :compounds, :fr_Nhpyrrole, :integer
      remove_column :compounds, :fr_SH, :integer
      remove_column :compounds, :fr_aldehyde, :integer
      remove_column :compounds, :fr_alkyl_carbamate, :integer
      remove_column :compounds, :fr_alkyl_halide, :integer
      remove_column :compounds, :fr_allylic_oxid, :integer
      remove_column :compounds, :fr_amide, :integer
      remove_column :compounds, :fr_amidine, :integer
      remove_column :compounds, :fr_aniline, :integer
      remove_column :compounds, :fr_aryl_methyl, :integer
      remove_column :compounds, :fr_azide, :integer
      remove_column :compounds, :fr_azo, :integer
      remove_column :compounds, :fr_barbitur, :integer
      remove_column :compounds, :fr_benzene, :integer
      remove_column :compounds, :fr_benzodiazepine, :integer
      remove_column :compounds, :fr_bicyclic, :integer
      remove_column :compounds, :fr_diazo, :integer
      remove_column :compounds, :fr_dihydropyridine, :integer
      remove_column :compounds, :fr_epoxide, :integer
      remove_column :compounds, :fr_ester, :integer
      remove_column :compounds, :fr_ether, :integer
      remove_column :compounds, :fr_furan, :integer
      remove_column :compounds, :fr_guanido, :integer
      remove_column :compounds, :fr_halogen, :integer
      remove_column :compounds, :fr_hdrzine, :integer
      remove_column :compounds, :fr_hdrzone, :integer
      remove_column :compounds, :fr_imidazole, :integer
      remove_column :compounds, :fr_imide, :integer
      remove_column :compounds, :fr_isocyan, :integer
      remove_column :compounds, :fr_isothiocyan, :integer
      remove_column :compounds, :fr_ketone, :integer
      remove_column :compounds, :fr_ketone_Topliss, :integer
      remove_column :compounds, :fr_lactam, :integer
      remove_column :compounds, :fr_lactone, :integer
      remove_column :compounds, :fr_methoxy, :integer
      remove_column :compounds, :fr_morpholine, :integer
      remove_column :compounds, :fr_nitrile, :integer
      remove_column :compounds, :fr_nitro, :integer
      remove_column :compounds, :fr_nitro_arom, :integer
      remove_column :compounds, :fr_nitro_arom_nonortho, :integer
      remove_column :compounds, :fr_nitroso, :integer
      remove_column :compounds, :fr_oxazole, :integer
      remove_column :compounds, :fr_oxime, :integer
      remove_column :compounds, :fr_para_hydroxylation, :integer
      remove_column :compounds, :fr_phenol, :integer
      remove_column :compounds, :fr_phenol_noOrthoHbond, :integer
      remove_column :compounds, :fr_phos_acid, :integer
      remove_column :compounds, :fr_phos_ester, :integer
      remove_column :compounds, :fr_piperdine, :integer
      remove_column :compounds, :fr_piperzine, :integer
      remove_column :compounds, :fr_priamide, :integer
      remove_column :compounds, :fr_prisulfonamd, :integer
      remove_column :compounds, :fr_pyridine, :integer
      remove_column :compounds, :fr_quatN, :integer
      remove_column :compounds, :fr_sulfide, :integer
      remove_column :compounds, :fr_sulfonamd, :integer
      remove_column :compounds, :fr_sulfone, :integer
      remove_column :compounds, :fr_term_acetylene, :integer
      remove_column :compounds, :fr_tetrazole, :integer
      remove_column :compounds, :fr_thiazole, :integer
      remove_column :compounds, :fr_thiocyan, :integer
      remove_column :compounds, :fr_thiophene, :integer
      remove_column :compounds, :fr_unbrch_alkane, :integer
      remove_column :compounds, :fr_urea, :integer
      remove_column :compounds, :qed, :float

      
          add_column :compounds, :avgipc, :float
          add_column :compounds, :bcut2d_chghi, :float
          add_column :compounds, :bcut2d_chglo, :float
          add_column :compounds, :bcut2d_logphi, :float
          add_column :compounds, :bcut2d_logplow, :float
          add_column :compounds, :bcut2d_mrhi, :float
          add_column :compounds, :bcut2d_mrlo, :float
          add_column :compounds, :bcut2d_mwhi, :float
          add_column :compounds, :bcut2d_mwlow, :float
          add_column :compounds, :balabanj, :float
          add_column :compounds, :bertzct, :float
          add_column :compounds, :chi0, :float
          add_column :compounds, :chi0n, :float
          add_column :compounds, :chi0v, :float
          add_column :compounds, :chi1, :float
          add_column :compounds, :chi1n, :float
          add_column :compounds, :chi1v, :float
          add_column :compounds, :chi2n, :float
          add_column :compounds, :chi2v, :float
          add_column :compounds, :chi3n, :float
          add_column :compounds, :chi3v, :float
          add_column :compounds, :chi4n, :float
          add_column :compounds, :chi4v, :float
          add_column :compounds, :estate_vsa1, :float
          add_column :compounds, :estate_vsa10, :float
          add_column :compounds, :estate_vsa11, :float
          add_column :compounds, :estate_vsa2, :float
          add_column :compounds, :estate_vsa3, :float
          add_column :compounds, :estate_vsa4, :float
          add_column :compounds, :estate_vsa5, :float
          add_column :compounds, :estate_vsa6, :float
          add_column :compounds, :estate_vsa7, :float
          add_column :compounds, :estate_vsa8, :float
          add_column :compounds, :estate_vsa9, :float
          add_column :compounds, :exactmolwt, :float
          add_column :compounds, :fpdensitymorgan1, :float
          add_column :compounds, :fpdensitymorgan2, :float
          add_column :compounds, :fpdensitymorgan3, :float
          add_column :compounds, :fractioncsp3, :float
          add_column :compounds, :hallkieralpha, :float
          add_column :compounds, :heavyatomcount, :integer
          add_column :compounds, :heavyatommolwt, :float
          add_column :compounds, :ipc, :float
          add_column :compounds, :kappa1, :float
          add_column :compounds, :kappa2, :float
          add_column :compounds, :kappa3, :float
          add_column :compounds, :labuteasa, :float
          add_column :compounds, :maxabsestateindex, :float
          add_column :compounds, :maxabspartialcharge, :float
          add_column :compounds, :maxestateindex, :float
          add_column :compounds, :maxpartialcharge, :float
          add_column :compounds, :minabsestateindex, :float
          add_column :compounds, :minabspartialcharge, :float
          add_column :compounds, :minestateindex, :float
          add_column :compounds, :minpartialcharge, :float
          add_column :compounds, :mollogp, :float
          add_column :compounds, :molmr, :float
          add_column :compounds, :molwt, :float
          add_column :compounds, :nhohcount, :integer
          add_column :compounds, :nocount, :integer
          add_column :compounds, :numaliphaticcarbocycles, :integer
          add_column :compounds, :numaliphaticheterocycles, :integer
          add_column :compounds, :numaliphaticrings, :integer
          add_column :compounds, :numaromaticcarbocycles, :integer
          add_column :compounds, :numaromaticheterocycles, :integer
          add_column :compounds, :numaromaticrings, :integer
          add_column :compounds, :numhacceptors, :integer
          add_column :compounds, :numhdonors, :integer
          add_column :compounds, :numheteroatoms, :integer
          add_column :compounds, :numradicalelectrons, :integer
          add_column :compounds, :numrotatablebonds, :integer
          add_column :compounds, :numsaturatedcarbocycles, :integer
          add_column :compounds, :numsaturatedheterocycles, :integer
          add_column :compounds, :numsaturatedrings, :integer
          add_column :compounds, :numvalenceelectrons, :integer
          add_column :compounds, :peoe_vsa1, :float
          add_column :compounds, :peoe_vsa10, :float
          add_column :compounds, :peoe_vsa11, :float
          add_column :compounds, :peoe_vsa12, :float
          add_column :compounds, :peoe_vsa13, :float
          add_column :compounds, :peoe_vsa14, :float
          add_column :compounds, :peoe_vsa2, :float
          add_column :compounds, :peoe_vsa3, :float
          add_column :compounds, :peoe_vsa4, :float
          add_column :compounds, :peoe_vsa5, :float
          add_column :compounds, :peoe_vsa6, :float
          add_column :compounds, :peoe_vsa7, :float
          add_column :compounds, :peoe_vsa8, :float
          add_column :compounds, :peoe_vsa9, :float
          add_column :compounds, :ringcount, :integer
          add_column :compounds, :smr_vsa1, :float
          add_column :compounds, :smr_vsa10, :float
          add_column :compounds, :smr_vsa2, :float
          add_column :compounds, :smr_vsa3, :float
          add_column :compounds, :smr_vsa4, :float
          add_column :compounds, :smr_vsa5, :float
          add_column :compounds, :smr_vsa6, :float
          add_column :compounds, :smr_vsa7, :float
          add_column :compounds, :smr_vsa8, :float
          add_column :compounds, :smr_vsa9, :float
          add_column :compounds, :slogp_vsa1, :float
          add_column :compounds, :slogp_vsa10, :float
          add_column :compounds, :slogp_vsa11, :float
          add_column :compounds, :slogp_vsa12, :float
          add_column :compounds, :slogp_vsa2, :float
          add_column :compounds, :slogp_vsa3, :float
          add_column :compounds, :slogp_vsa4, :float
          add_column :compounds, :slogp_vsa5, :float
          add_column :compounds, :slogp_vsa6, :float
          add_column :compounds, :slogp_vsa7, :float
          add_column :compounds, :slogp_vsa8, :float
          add_column :compounds, :slogp_vsa9, :float
          add_column :compounds, :tpsa, :float
          add_column :compounds, :vsa_estate1, :float
          add_column :compounds, :vsa_estate10, :float
          add_column :compounds, :vsa_estate2, :float
          add_column :compounds, :vsa_estate3, :float
          add_column :compounds, :vsa_estate4, :float
          add_column :compounds, :vsa_estate5, :float
          add_column :compounds, :vsa_estate6, :float
          add_column :compounds, :vsa_estate7, :float
          add_column :compounds, :vsa_estate8, :float
          add_column :compounds, :vsa_estate9, :float
          add_column :compounds, :fr_al_coo, :integer
          add_column :compounds, :fr_al_oh, :integer
          add_column :compounds, :fr_al_oh_notert, :integer
          add_column :compounds, :fr_arn, :integer
          add_column :compounds, :fr_ar_coo, :integer
          add_column :compounds, :fr_ar_n, :integer
          add_column :compounds, :fr_ar_nh, :integer
          add_column :compounds, :fr_ar_oh, :integer
          add_column :compounds, :fr_coo, :integer
          add_column :compounds, :fr_coo2, :integer
          add_column :compounds, :fr_c_o, :integer
          add_column :compounds, :fr_c_o_nocoo, :integer
          add_column :compounds, :fr_c_s, :integer
          add_column :compounds, :fr_hoccn, :integer
          add_column :compounds, :fr_imine, :integer
          add_column :compounds, :fr_nho, :integer
          add_column :compounds, :fr_nh1, :integer
          add_column :compounds, :fr_nh2, :integer
          add_column :compounds, :fr_n_o, :integer
          add_column :compounds, :fr_ndealkylation1, :integer
          add_column :compounds, :fr_ndealkylation2, :integer
          add_column :compounds, :fr_nhpyrrole, :integer
          add_column :compounds, :fr_sh, :integer
          add_column :compounds, :fr_aldehyde, :integer
          add_column :compounds, :fr_alkyl_carbamate, :integer
          add_column :compounds, :fr_alkyl_halide, :integer
          add_column :compounds, :fr_allylic_oxid, :integer
          add_column :compounds, :fr_amide, :integer
          add_column :compounds, :fr_amidine, :integer
          add_column :compounds, :fr_aniline, :integer
          add_column :compounds, :fr_aryl_methyl, :integer
          add_column :compounds, :fr_azide, :integer
          add_column :compounds, :fr_azo, :integer
          add_column :compounds, :fr_barbitur, :integer
          add_column :compounds, :fr_benzene, :integer
          add_column :compounds, :fr_benzodiazepine, :integer
          add_column :compounds, :fr_bicyclic, :integer
          add_column :compounds, :fr_diazo, :integer
          add_column :compounds, :fr_dihydropyridine, :integer
          add_column :compounds, :fr_epoxide, :integer
          add_column :compounds, :fr_ester, :integer
          add_column :compounds, :fr_ether, :integer
          add_column :compounds, :fr_furan, :integer
          add_column :compounds, :fr_guanido, :integer
          add_column :compounds, :fr_halogen, :integer
          add_column :compounds, :fr_hdrzine, :integer
          add_column :compounds, :fr_hdrzone, :integer
          add_column :compounds, :fr_imidazole, :integer
          add_column :compounds, :fr_imide, :integer
          add_column :compounds, :fr_isocyan, :integer
          add_column :compounds, :fr_isothiocyan, :integer
          add_column :compounds, :fr_ketone, :integer
          add_column :compounds, :fr_ketone_topliss, :integer
          add_column :compounds, :fr_lactam, :integer
          add_column :compounds, :fr_lactone, :integer
          add_column :compounds, :fr_methoxy, :integer
          add_column :compounds, :fr_morpholine, :integer
          add_column :compounds, :fr_nitrile, :integer
          add_column :compounds, :fr_nitro, :integer
          add_column :compounds, :fr_nitro_arom, :integer
          add_column :compounds, :fr_nitro_arom_nonortho, :integer
          add_column :compounds, :fr_nitroso, :integer
          add_column :compounds, :fr_oxazole, :integer
          add_column :compounds, :fr_oxime, :integer
          add_column :compounds, :fr_para_hydroxylation, :integer
          add_column :compounds, :fr_phenol, :integer
          add_column :compounds, :fr_phenol_noOrthoHbond, :integer
          add_column :compounds, :fr_phos_acid, :integer
          add_column :compounds, :fr_phos_ester, :integer
          add_column :compounds, :fr_piperdine, :integer
          add_column :compounds, :fr_piperzine, :integer
          add_column :compounds, :fr_priamide, :integer
          add_column :compounds, :fr_prisulfonamd, :integer
          add_column :compounds, :fr_pyridine, :integer
          add_column :compounds, :fr_quatN, :integer
          add_column :compounds, :fr_sulfide, :integer
          add_column :compounds, :fr_sulfonamd, :integer
          add_column :compounds, :fr_sulfone, :integer
          add_column :compounds, :fr_term_acetylene, :integer
          add_column :compounds, :fr_tetrazole, :integer
          add_column :compounds, :fr_thiazole, :integer
          add_column :compounds, :fr_thiocyan, :integer
          add_column :compounds, :fr_thiophene, :integer
          add_column :compounds, :fr_unbrch_alkane, :integer
          add_column :compounds, :fr_urea, :integer
          add_column :compounds, :qed, :float
        
    end
  end
  